### ISSUE TITLE
compile error on server startup "Unknown type: 'EditorDeletedObjectData'"

### ISSUE THREAD

**Issue by Revertal** [InclementDab/DayZ-Editor-Loader#2]
@InclementDab
In File https://github.com/InclementDab/DayZ-Editor-Loader/blob/main/DayZEditorLoader/Scripts/5_Mission/DayZEditorLoader/Mission/EditorLoaderModule.c line 1

From the logs:
***
23:48:29.429 SCRIPT    (E): @"DayZEditorLoader/scripts/5_Mission/dayzeditorloader\mission\editorloadermodule.c,1": Unknown type 'EditorDeletedObjectData'

23:48:29.429 SCRIPT    (E): @"DayZEditorLoader/scripts/5_Mission/dayzeditorloader\mission\editorloadermodule.c,1": Wrong number of template parameters

23:48:29.448 SCRIPT    (E): @"DayZEditorLoader/scripts/5_Mission/dayzeditorloader\mission\editorloadermodule.c,8": Unknown type 'EditorSaveData'

23:48:29.448 SCRIPT    (E): @"DayZEditorLoader/scripts/5_Mission/dayzeditorloader\mission\editorloadermodule.c,8": Wrong number of template parameters

23:48:29.448 SCRIPT    (E): @"DayZEditorLoader/scripts/5_Mission/dayzeditorloader\mission\editorloadermodule.c,39": Unknown type 'EditorSaveData'

23:48:29.448 SCRIPT    (E): @"DayZEditorLoader/scripts/5_Mission/dayzeditorloader\mission\editorloadermodule.c,59": Unknown type 'EditorSaveData'

23:48:29.691 SCRIPT    (E): Can't compile "Mission" script module!

DayZEditorLoader/scripts/5_Mission/dayzeditorloader\mission\editorloadermodule.c(1): Unknown type 'EditorDeletedObjectData'

***

Nice editor by the way, but still could need some polishment ;)

**Comment by InclementDab** [comment]
You arent running Dabs Framework, its in the dependency list on the workshop.

> Nice editor by the way, but still could need some polishment ;)

what? im one guy what do you expect. make a better one lol
